### ISSUE TITLE
/bin/install: cannot stat ‘.//README.external_file’: No such file or directory

### ISSUE THREAD

**Issue by xinferum** [darold/external_file#1]
Good day!

When installing the extension, I encountered an error:
```
/bin/install: cannot stat ‘.//README.external_file’: No such file or directory
make: *** [install] Error 1
```
The error is caused by a missing file **README.external_file** in repository. As I understand it, the content of this file was meant to be similar to the README.md file.
As a solution to this problem, I propose to add in the Makefile the creation of the desired file from README.md:
```
all: prepare_readme

prepare_readme: README.md
	@echo "Prepare README.external_file"
	cp README.md README.external_file
```
The whole Makefile will look like this:
```
#MODULES = external_file
EXTENSION = external_file
DATA = external_file--1.0.sql
DOCS = README.external_file

PG_CONFIG = pg_config
PGXS := $(shell $(PG_CONFIG) --pgxs)
include $(PGXS)

all: prepare_readme

prepare_readme: README.md
	@echo "Prepare README.external_file"
	cp README.md README.external_file
```

**Comment by darold** [comment]
Sorry for the response delay, commit 62b38af applies your patch, thanks.

**Comment by xinferum** [comment]
Thanks! The build now runs without errors.
